version: '3.8'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb/
    env_file: .env
    volumes:
      - mariadb_vol:/var/lib/mysql
    restart: always
    expose:
      - "3306"
 
  nginx:
    container_name: nginx
    volumes:
      - wordpress_vol:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    env_file: .env
    ports:
      - "443:443"
    restart: always

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress_vol:/var/www/wordpress
    networks:
      - inception
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: always
    expose: 
      - "9000"

  volumes:
    mariadb_vol:
      driver_opts:
        o: bind
        type: none
        device: /home/devm/data/db
    wordpress_vol:
      driver_opts:
        o: bind
        type: none
        device: /home/devm/data/wp
  networks:
    inception:
      driver: bridge