version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    image: mariadb
    restart: always
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE : ${MYSQL_DATABASE}
      MYSQL_USER : ${MYSQL_USER}
      MYSQL_PASSWORD : ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD : ${MYSQL_ROOT_PASSWORD}
 
  nginx:
    container_name: nginx
    build: 
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    image: nginx
    restart: always
    volumes:
      - wordpress_vol:/var/www/html/wordpress
      - adminer_vol:/var/www/html/adminer
      - tempo_vol:/var/www/html/tempo
    networks:
      - inception
    depends_on:
      - wordpress
      - adminer
      - tempo
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    restart: always
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    expose: 
      - "9000"
    environment:
      MYSQL_DATABASE : ${MYSQL_DATABASE}
      MYSQL_USER : ${MYSQL_USER}
      MYSQL_PASSWORD : ${MYSQL_PASSWORD}
      WP_URL : ${WP_URL}
      WP_TITLE : ${WP_TITLE}
      WP_ADMIN : ${WP_ADMIN}
      WP_ADMIN_PASSWD : ${WP_ADMIN_PASSWD}
      WP_ADMIN_EMAIL : ${WP_ADMIN_EMAIL}
      WP_USER : ${WP_USER}
      WP_USER_EMAIL : ${WP_USER_EMAIL}
      WP_USER_PASSWD : ${WP_USER_PASSWD}

  adminer:
    container_name: adminer
    build: 
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    image: adminer
    restart: always
    volumes:
      - adminer_vol:/var/www/html/adminer
    networks:
      - inception
    depends_on:
      - mariadb
    expose: 
      - "8080"
  tempo:
    container_name: tempo
    build: 
      context: ./requirements/bonus/tempo
      dockerfile: Dockerfile
    image: tempo
    volumes:
      - tempo_vol:/var/www/html/tempo
    networks:
      - inception
    restart: always

volumes:
  mariadb_vol:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wordpress_vol:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  adminer_vol:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/adminer
  tempo_vol:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/tempo
networks:
  inception:
    driver: bridge
